round6-bootcamp/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Numero do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Usado para informar se o jogador foi eliminado</description>
    <inlineHelpText>Jogador eliminado ?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <description>Usado para informar o jogo em que o participante jogou</description>
    <inlineHelpText>Usado para informar o jogo em que o participante jogou</inlineHelpText>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>Usado para representar o jogo da série &quot; Round 6&quot;</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Round__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status do Round</description>
    <inlineHelpText>Status do Round</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em definição</fullName>
                <default>true</default>
                <label>Em definição</label>
            </value>
            <value>
                <fullName>Coletando Candidatos</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Round__c/fields/Vencedor__c.field-meta.xml
<CustomField>
    <fullName>Vencedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Vencedor do round</description>
    <inlineHelpText>Vencedor do round</inlineHelpText>
    <label>Vencedor</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <type>Lookup</type>
</CustomField>

round6-bootcamp/force-app/main/default/classes/JogadoresTriggerHandlerTest.cls
@isTest
public with sharing class JogadoresTriggerHandlerTest {
    @TestSetup
    static void setup() {

        Round__c round = new Round__c(Status__c='Em Andamento');
        List<Round__c> rounds = new List<Round__c>();
        rounds.add(round);
        insert rounds;

        Jogador__c jogador1 = new Jogador__c(Round__c=round.Id,Eliminado__c= false);
        Jogador__c jogador2 = new Jogador__c(Round__c=round.Id, Eliminado__c= true);
      
         List<Jogador__c> jogadores = new List<Jogador__c>();
         jogadores.add(jogador1);
         jogadores.add(jogador2);
        // rounds.add(r2);    
         insert jogadores;
         
    }

    @isTest
    static void handleVencedorTest() {
        List<Jogador__c> jogadores = [SELECT id,Eliminado__c,Round__c FROM Jogador__c];

        System.debug('jogadores: ' + JSON.serialize(jogadores));

        
        Map<Id, Round__c> roundsMap = new Map<Id, Round__c>([SELECT Id,Vencedor__c,  (SELECT Id FROM Jogadores__r WHERE Eliminado__c = false) FROM Round__c]);

        Map<Id, Round__c> roundsToUpdate = new Map<Id, Round__c>();
        System.debug('roundsMap: ' + JSON.serialize(roundsMap));

        Test.startTest();
        for (Jogador__c jogador : jogadores) {

            System.debug('jogador.Round__c: ' + jogador.Round__c);

            JogadoresTriggerHandler.handleVencedor(jogador,roundsMap.get(jogador.Round__c),roundsToUpdate); 
        }
        

        System.debug('UPDATE roundsToUpdate: ' + roundsToUpdate);
        Test.stopTest();
       
       
        for (Jogador__c jogador: jogadores)
        {
            if (!jogador.Eliminado__c){
                System.assertEquals(jogador.Id, roundsToUpdate.get(jogador.Round__c).Vencedor__c, 'O jogador vencedor deve ser ->' +jogador.Id);
            }
        }
        

        

    }
}