round6-bootcamp/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Numero do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Forca__c.field-meta.xml
<CustomField>
    <fullName>Forca__c</fullName>
    <defaultValue>1</defaultValue>
    <description>força do jogador</description>
    <inlineHelpText>força do jogador</inlineHelpText>
    <label>Força</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Velocidade__c.field-meta.xml
<CustomField>
    <fullName>Velocidade__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Velocidade do jogador</description>
    <inlineHelpText>Velocidade do jogador</inlineHelpText>
    <label>Velocidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

round6-bootcamp/force-app/main/default/classes/UtilsTest.cls
@isTest
public with sharing class UtilsTest {
    
    @isTest
    static void testSetValueException() {
        Jogador__c jog = new Jogador__c();
        String errorMessage;
        
        Test.startTest();
        try {
            Utils.setValue(jog, Jogador__c.Name, 'Renato');
        } catch (Exception e) {
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        System.assert(errorMessage.contains('Field Name is not editable'), 'O campo name não deveria ser editável');
    }

    @isTest
    static void testSetValue() {
        Jogador__c jog = new Jogador__c();
        Integer vel = 10;
        Integer frc = 30;

        
        Test.startTest();
        Utils.setValue(jog, Jogador__c.Velocidade__c, vel);
        Utils.setValue(jog, Jogador__c.Forca__c, frc);
        Test.stopTest();

        System.assertEquals(jog.Velocidade__c, vel, 'A velocidade deveria ser ' + vel);
        System.assertEquals(jog.Forca__c, frc, 'A força deveria ser ' + frc);
    }
    

}