round6-bootcamp/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Numero do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <description>Usado para informar o jogo em que o participante jogou</description>
    <inlineHelpText>Usado para informar o jogo em que o participante jogou</inlineHelpText>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/ValorPagar__c.field-meta.xml
<CustomField>
    <fullName>ValorPagar__c</fullName>
    <label>Valor a pagar</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>Usado para representar o jogo da série &quot; Round 6&quot;</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Round__c/fields/Premio__c.field-meta.xml
<CustomField>
    <fullName>Premio__c</fullName>
    <description>Prêmio total do jogo</description>
    <formula>5000000 *  TotalDeJogadoresEliminados__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Prêmio total do jogo</inlineHelpText>
    <label>Prêmio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Round__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status do Round</description>
    <inlineHelpText>Status do Round</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em definição</fullName>
                <default>true</default>
                <label>Em definição</label>
            </value>
            <value>
                <fullName>Coletando Candidatos</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

round6-bootcamp/force-app/main/default/classes/RoundsTriggerHandler.cls
public without sharing class RoundsTriggerHandler {    

    static FINAL String STATUS_ROUND_SUSPENSO = 'Suspenso';
    static FINAL String STATUS_ROUND_FINALIZADO = 'Finalizado';

    public static void afterUpdate(List<Round__c> records, Map<Id, Round__c> oldMap) {
        Map<Id, Round__c> recordsWithJogadoresMap = new Map<Id, Round__c>(RoundsSelector.selectByRoundsIdsWithJogadores(oldMap.keySet()));
        List<Jogador__c> jogadoresToUpdate = new List<Jogador__c>();

        for (Round__c record : records) {
            afterUpdate(record, oldMap.get(record.Id), recordsWithJogadoresMap.get(record.Id).Jogadores__r, jogadoresToUpdate);
        }

        update jogadoresToUpdate;
    }

    private static void afterUpdate(Round__c record, Round__c recordOld, List<Jogador__c> jogadoresRound, List<Jogador__c> jogadoresToUpdate) {
        handleSuspensao(record, recordOld, jogadoresRound, jogadoresToUpdate);
    }

    //TODO: não pagar família de membro do staff e cálculo não deverá considerá-lo como um jogador
    private static void handleSuspensao(Round__c record, Round__c recordOld, List<Jogador__c> jogadoresRound, List<Jogador__c> jogadoresToUpdate) {
        if (!jogadoresRound.isEmpty() && roundFinalizadoPorSuspensao(record.Status__c, recordOld.Status__c)) {
            setValorPagarMortos(getPremioReal(record.Premio__c, jogadoresRound), jogadoresRound);
            
            jogadoresToUpdate.addAll(jogadoresRound);
        }
    }

    private static Boolean roundFinalizadoPorSuspensao(String status, String statusOld) {
        return statusOld.equals(STATUS_ROUND_SUSPENSO) && status.equals(STATUS_ROUND_FINALIZADO);
    }

    private static void setValorPagarMortos(Decimal premio, List<Jogador__c> jogadoresRound) {
        Decimal premioReal = getPremioReal(premio, jogadoresRound);

        for (Jogador__c jogador : jogadoresRound) {
            if (isMembroStaff(jogador.RecordType.DeveloperName)) {
                Utils.setValue(jogador, Jogador__c.ValorPagar__c, premioReal);
            }
        }
    }

    private static Decimal getPremioReal(Decimal premio, List<Jogador__c> jogadoresRound) {
        Integer qtdMembroStaff = 0;

        for (Jogador__c jogador : jogadoresRound) {
            if (isMembroStaff(jogador.RecordType.DeveloperName)) {
                qtdMembroStaff++;
            }
        }
        
        return calculaPremioUnitarioReal(premio, jogadoresRound.size(), qtdMembroStaff);
    }

    private static Boolean isMembroStaff(String recordTypeDeveloperName) {
        return recordTypeDeveloperName.equals(Label.RECORD_TYPE_DEVELOPER_NAME_MEMBRO_STAFF);
    }

    private static Decimal calculaPremioUnitarioReal(Decimal premio, Integer qtdJogadores, Integer qtdMembroStaff) {
        Decimal premioUnitario = premio/qtdJogadores;
        Decimal premioNaoConsiderandoStaff = premio - (premioUnitario*qtdMembroStaff);
        Decimal qtdJogadoresValidos = qtdJogadores - qtdMembroStaff;

        return premioNaoConsiderandoStaff/qtdJogadoresValidos;
    }
}