round6-bootcamp/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Numero do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Inteligencia__c.field-meta.xml
<CustomField>
    <fullName>Inteligencia__c</fullName>
    <defaultValue>1</defaultValue>
    <description>inteligencia do jogador</description>
    <inlineHelpText>inteligencia do jogador</inlineHelpText>
    <label>Inteligencia</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Velocidade__c.field-meta.xml
<CustomField>
    <fullName>Velocidade__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Velocidade do jogador</description>
    <inlineHelpText>Velocidade do jogador</inlineHelpText>
    <label>Velocidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

round6-bootcamp/force-app/main/default/classes/Defensor.cls
public class Defensor {
   
    Jogador__c jogador;
    
    public Defensor(Jogador__c jogador) {
       this.jogador = jogador;                
    }

    public Decimal rolarDado() {//d10
        return Utils.generateRandomNumber(1,10);
    }

    public Decimal poder() {
        return 
            rolarDado() + rolarDado()
            + jogador.Inteligencia__c //verificar se é null
            + jogador.Velocidade__c;            
    }

    public Jogador__c jogador() {
        return jogador;
    }

}