round6-bootcamp/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Numero do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Usado para informar se o jogador foi eliminado</description>
    <inlineHelpText>Jogador eliminado ?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Forca__c.field-meta.xml
<CustomField>
    <fullName>Forca__c</fullName>
    <defaultValue>1</defaultValue>
    <description>força do jogador</description>
    <inlineHelpText>força do jogador</inlineHelpText>
    <label>Força</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Inteligencia__c.field-meta.xml
<CustomField>
    <fullName>Inteligencia__c</fullName>
    <defaultValue>1</defaultValue>
    <description>inteligencia do jogador</description>
    <inlineHelpText>inteligencia do jogador</inlineHelpText>
    <label>Inteligencia</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <description>Usado para informar o jogo em que o participante jogou</description>
    <inlineHelpText>Usado para informar o jogo em que o participante jogou</inlineHelpText>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Velocidade__c.field-meta.xml
<CustomField>
    <fullName>Velocidade__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Velocidade do jogador</description>
    <inlineHelpText>Velocidade do jogador</inlineHelpText>
    <label>Velocidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>Usado para representar o jogo da série &quot; Round 6&quot;</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Round__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status do Round</description>
    <inlineHelpText>Status do Round</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em definição</fullName>
                <default>true</default>
                <label>Em definição</label>
            </value>
            <value>
                <fullName>Coletando Candidatos</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

round6-bootcamp/force-app/main/default/classes/JogadoresSelector.cls
public with sharing class JogadoresSelector {
    
    
    public static List<Jogador__c> selectJogadoresByRound(Set<Id> ids) {
        return [
            
        SELECT Id,Round__c 
        FROM Jogador__c 
        WHERE Round__c IN :ids
        AND Eliminado__c = false
        
        ];
    }
    public static List<Jogador__c> selectJogadoresVivosByRoundStatus() {
        return [select ID,Forca__c,Velocidade__c,Inteligencia__c from Jogador__c 
        where
        Morreu__c = false and
        Round__r.Status__c= 'Em andamento'];
    }

}