round6-bootcamp/force-app/main/default/objects/Candidato__c/Candidato__c.object-meta.xml
<CustomObject>
    <description>Um candidato é uma pessoa que foi convidada para participar dos jogos mas ainda não aceitou</description>
    <label>Candidato</label>
    <nameField>
        <label>Nome do Candidato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Numero do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Candidato__c.field-meta.xml
<CustomField>
    <fullName>Candidato__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Referente ao registro do candidato</description>
    <inlineHelpText>Referente ao registro do candidato</inlineHelpText>
    <label>Candidato</label>
    <referenceTo>Candidato__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <type>Lookup</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Usado para informar se o jogador foi eliminado</description>
    <inlineHelpText>Jogador eliminado ?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <description>Usado para informar o jogo em que o participante jogou</description>
    <inlineHelpText>Usado para informar o jogo em que o participante jogou</inlineHelpText>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/ValorPagar__c.field-meta.xml
<CustomField>
    <fullName>ValorPagar__c</fullName>
    <label>Valor a pagar</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>Usado para representar o jogo da série &quot; Round 6&quot;</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Round__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status do Round</description>
    <inlineHelpText>Status do Round</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em definição</fullName>
                <default>true</default>
                <label>Em definição</label>
            </value>
            <value>
                <fullName>Coletando Candidatos</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Round__c/fields/TotalDeJogadoresEliminados__c.field-meta.xml
<CustomField>
    <fullName>TotalDeJogadoresEliminados__c</fullName>
    <description>Usado para informar o total de jogadores eliminados</description>
    <inlineHelpText>Total de jogadores eliminados</inlineHelpText>
    <label>Total de Jogadores Eliminados</label>
    <summaryFilterItems>
        <field>Jogador__c.Eliminado__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Jogador__c.Round__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Round__c/fields/Vencedor__c.field-meta.xml
<CustomField>
    <fullName>Vencedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Vencedor do round</description>
    <inlineHelpText>Vencedor do round</inlineHelpText>
    <label>Vencedor</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Rounds</relationshipLabel>
    <relationshipName>Rounds</relationshipName>
    <type>Lookup</type>
</CustomField>

round6-bootcamp/force-app/main/default/classes/RoundsSelector.cls
public without sharing class RoundsSelector {

    public static List<Round__c> selectByRoundsIdsWithJogadores(Set<Id> ids) {
        return [
            SELECT  Id, TotalDeJogadoresEliminados__c, PremioTotal__c,
                    (
                        SELECT Id, ValorPagar__c, RecordTypeId, RecordType.DeveloperName, Candidato__r.Email__c
                        FROM Jogadores__r 
                        WHERE Eliminado__c = true
                    )
            FROM Round__c 
            WHERE Id IN :ids
        ];
    }

    public static List<Round__c> selectRoundsByIdStatusJogadoresVivos(Set<Id> roundsIds, Set<String> statusList) {
        return [
            SELECT 
                Id,
                Vencedor__c,
                (SELECT Id FROM Jogadores__r WHERE Eliminado__c = false)
            FROM Round__c
            WHERE 
                    Id = :roundsIds          
                AND Status__c IN :statusList
        ];
    }

}