round6-bootcamp/force-app/main/default/objects/Candidato__c/Candidato__c.object-meta.xml
<CustomObject>
    <description>Um candidato é uma pessoa que foi convidada para participar dos jogos mas ainda não aceitou</description>
    <label>Candidato</label>
    <nameField>
        <label>Nome do Candidato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Candidato__c/fields/Celular__c.field-meta.xml
<CustomField>
    <fullName>Celular__c</fullName>
    <description>Usado para entrar em contato com o candidato</description>
    <inlineHelpText>Forma de contato</inlineHelpText>
    <label>Celular</label>
    <type>Phone</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Candidato__c/fields/DataNascimento__c.field-meta.xml
<CustomField>
    <fullName>DataNascimento__c</fullName>
    <defaultValue>now()</defaultValue>
    <description>Data que o candidato nasceu registrado na certidão de nascimento. (usada no calculo de idade)</description>
    <inlineHelpText>Data que o candidato nasceu registrado na certidão de nascimento.</inlineHelpText>
    <label>Data de Nascimento</label>
    <type>Date</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Candidato__c/fields/ValorDaDivida__c.field-meta.xml
<CustomField>
    <fullName>ValorDaDivida__c</fullName>
    <description>Valor total da dívida do candidato com agiotas ou bancos.</description>
    <inlineHelpText>Valor total da dívida do candidato com agiotas ou bancos.</inlineHelpText>
    <label>Valor da Dívida</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

round6-bootcamp/force-app/main/default/classes/GetCandidatosApi.cls
global class GetCandidatosApi {

    @Future(callout=true)
    global static void addCandidatos(List<Integer> request){
       List<Candidato__c> listCandidatosResponse = new List<Candidato__c>();
       Integer qtdGerar = request.get(0);
        
       List<Candidato> listC = CalloutCandidatoHeroku.getCandidatos(qtdGerar);
        
        for(Candidato candidato : listC){//todo: refatorar metodo add.
            Candidato__c cAux = new Candidato__c();
            cAux.Name = candidato.nome;
            cAux.Email__c = candidato.email;
            cAux.Celular__c = candidato.celular;
            caux.DataNascimento__c = Date.valueOf(candidato.dataNascimento);
            cAux.ValorDaDivida__c = candidato.valorDivida;
            
            listCandidatosResponse.add(cAux);
        }
        
        insert listCandidatosResponse;
       
    }
     
}