round6-bootcamp/force-app/main/default/objects/Assassinato__c/Assassinato__c.object-meta.xml
<CustomObject>
    <label>Assassinato</label>
    <nameField>
        <displayFormat>ASS-{0000}</displayFormat>
        <label>Número do Assassinato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assassinatos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Numero do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <description>Usado para informar o jogo em que o participante jogou</description>
    <inlineHelpText>Usado para informar o jogo em que o participante jogou</inlineHelpText>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>Usado para representar o jogo da série &quot; Round 6&quot;</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/classes/SimulacaoContainerController.cls
public with sharing class SimulacaoContainerController {
    @AuraEnabled(cacheable=true)
    public static List<Round__c> getRoundsJogadores() {
        try {
            return RoundsSelector.selectAllRoundsWithJogadoresNaoEliminados();
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static AssassinatoWrapper tentativaAssassinato(List<Jogador__c> jogadores) {
        try {     
            Assassinato__c ass = AssassinatosHandler.execute(jogadores);
            if (ass != null) {
                insert ass;
            
                Jogador__c jog = new Jogador__c(Id=ass.Assassinado__c);
                jog.Morreu__c = true;
                update jog;
            }      
            
            AssassinatoWrapper aw = new AssassinatoWrapper();
            aw.Assassinato = ass;
            aw.Rounds = RoundsSelector.selectAllRoundsWithJogadoresNaoEliminados();
            
            return aw;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }   
    
    public class AssassinatoWrapper {
        @AuraEnabled
        public Assassinato__c Assassinato;
        @AuraEnabled
        public List<Round__c> Rounds;
    }
}