round6-bootcamp/force-app/main/default/objects/Assassinato__c/Assassinato__c.object-meta.xml
<CustomObject>
    <label>Assassinato</label>
    <nameField>
        <displayFormat>ASS-{0000}</displayFormat>
        <label>Número do Assassinato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assassinatos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Numero do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Forca__c.field-meta.xml
<CustomField>
    <fullName>Forca__c</fullName>
    <defaultValue>1</defaultValue>
    <description>força do jogador</description>
    <inlineHelpText>força do jogador</inlineHelpText>
    <label>Força</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Inteligencia__c.field-meta.xml
<CustomField>
    <fullName>Inteligencia__c</fullName>
    <defaultValue>1</defaultValue>
    <description>inteligencia do jogador</description>
    <inlineHelpText>inteligencia do jogador</inlineHelpText>
    <label>Inteligencia</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

round6-bootcamp/force-app/main/default/objects/Jogador__c/fields/Velocidade__c.field-meta.xml
<CustomField>
    <fullName>Velocidade__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Velocidade do jogador</description>
    <inlineHelpText>Velocidade do jogador</inlineHelpText>
    <label>Velocidade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

round6-bootcamp/force-app/main/default/classes/AssassinatoHandler.cls
public class AssassinatoHandler {
    public AssassinatoHandler() {

    }
    @future
    public static void execute(){  
        System.debug('iniciou -> ');
    
        disputar();
    }


    static void disputar() {

        List<Jogador__c> jogadores = JogadoresSelector.selectJogadoresVivos();

        //todo verificar se os numeros gerados sao iguais
        System.debug('jogadores -> '+ jogadores);

        Integer ramdonAtacante = Utils.generateRandomNumber(0,jogadores.size()-1);
        Integer ramdonDefensor = Utils.generateRandomNumber(0,jogadores.size()-1);
        Jogador__c atacante = jogadores[ramdonAtacante];
        Jogador__c defensor = jogadores[ramdonDefensor]; 


        Integer forcaAtacante =getForcaAtacante(atacante);
        Integer forcaDefensor = getForcaDefensor(defensor);
        
        System.debug('forcaAtacante -> '+ forcaAtacante);

        System.debug('forcaDefensor -> '+ forcaDefensor);


        if (forcaAtacante > forcaDefensor) {
            
            assassinar(atacante,defensor);
           
        } else if (( forcaAtacante == 1)  && (forcaDefensor > forcaAtacante)) {
            assassinar(defensor,atacante);

        }
    }
    private static Integer getForcaAtacante(Jogador__c assassino) {
        return Utils.getD20() + assassino.Forca__c.intValue();

    }
    private static Integer getForcaDefensor(Jogador__c assassinado) {
        return (Utils.getD10() + Utils.getD10() ) + assassinado.Inteligencia__c.intValue() + assassinado.Velocidade__c.intValue();

    }

    private static void assassinar(Jogador__c assassino, Jogador__c assassinado) {
        System.debug('matou -> '+ assassinado);
        Assassinato__c assinato = new Assassinato__c (
            Assassinado__c = assassinado.Id,
            Assassino__c = assassino.Id,
            DataHora__c = System.now()
            );
        insert assinato;
    }

    

}